[tool.poetry]
name = "settings"
version = "0.1.0"
description = "ğŸ˜ Un bot qui annonce le calendrier rÃ©volutionnaire franÃ§ais ğŸ˜"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mastodon-py = "*"
repcal = "*"

[tool.mypy]
strict = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
